version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    nodejs: "20"
  jobs:
    install:
        # Since the install step is overridden, pip is no longer updated automatically.
        - pip install --upgrade pip
        - pip install --group 'docs' .

    pre_build:
      # Generate the Sphinx configuration for this Jupyter Book, so it builds.
      - "jupyter-book config sphinx docs/"

sphinx:
  builder: html
  fail_on_warning: true
  configuration: docs/conf.py
